name: Build

on:
  push:
    branches: [ add-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fp3d
    - name: Copy binaries
      run: |
        docker create --name fp3d fp3d
        docker cp fp3d:/app/build/dist dist
        docker rm fp3d
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux build
        path: dist
